### ISSUE TITLE
How to prepare a custom training data ?

### ISSUE THREAD

**Issue by kingsley351** [mxhofer/Named-Entity-Recognition-BidirectionalLSTM-CNN-CoNLL#7]
Is there any tool to annotate words and gives this format of train.txt ?

**Comment by mxhofer** [comment]
The following repository contains the code I used to convert medical text data to the CoNLL train.txt format: https://github.com/mxhofer/i2b2_2009-to-CoNLL 
This article provides additional details: https://towardsdatascience.com/deep-learning-for-named-entity-recognition-3-reusing-a-bidirectional-lstm-cnn-on-clinical-text-e84bd28052df
Hope this helps!
